import { Component } from '@angular/core';

@Component({
  selector: 'app-invoice-details',
  imports: [],
  templateUrl: './invoice-details.component.html',
  styleUrl: './invoice-details.component.scss'
})
export class InvoiceDetailsComponent {
  items = [
    { label: 'City:', value: 'ADQ' },
    { label: 'Client:', value: 'Alaska Airlines' },
    { label: 'Invoice Status:', value: 'Submitted' },
    { label: 'Sub-Status:', value: 'Pending Auditor Review' },
    { label: 'Hotel Invoice No:', value: 'S-56952811' }
    , { label: 'API Supplier Number:', value: '100055-002' }
    , { label: 'Vendor ID:', value: '-' }
    , { label: 'Generated By:', value: 'System' },
    { label: 'Start Date:', value: '01 May 2025' },
    { label: 'Generated By:', value: '31 May 2025' },
    { label: 'Submit Date:', value: '01 Jul 2025' },
  ];

  

}
